apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-svc
  name: mariadb-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30011
  selector:
    app: mysql-order-pod-appc
  type: NodePort
